version: '3.8'
services:
  dev-db:
    image: postgres:13.2
    container_name: dev-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: personal_site
    ports:
      - 5434:5432

networks:
  personal-site:
